server.port=8080
spring.application.name=buzzboard-backend

spring.datasource.url=jdbc:postgresql://buzzboard-prod-postgres.cxq286g2c50t.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Buzzboard123!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
