name: Backend CI

on:
push:
branches:
- main
paths:
- "backend/**"
- ".github/workflows/backend-ci.yml"

workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout source code
    uses: actions/checkout@v4

  - name: Set up Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: "17"

  - name: Build Backend
    working-directory: backend
    run: |
      chmod +x mvnw
      ./mvnw clean package -DskipTests

  - name: Build Docker image
    working-directory: backend
    run: |
      docker build -t buzzboard-backend:${{ github.sha }} .
```

